name: real_estate
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluentui_icons: ^1.0.0
  gap: ^3.0.0
  get:
  flutter_svg: ^2.0.5
  http: ^0.13.6
  shimmer: ^2.0.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.1
  flutter_expandable_text: ^1.0.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  otp_timer_button: ^1.1.0
  calendar_timeline: ^1.1.2
  mrx_charts: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
#    - assets/images/controls/

  fonts:
  - family: Outfit
    fonts:
      - asset: fonts/Outfit-ExtraLight.ttf
        weight: 200
      - asset: fonts/Outfit-Light.ttf
        weight: 300
      - asset: fonts/Outfit-Regular.ttf
        weight: 400
      - asset: fonts/Outfit-Medium.ttf
        weight: 500
      - asset: fonts/Outfit-SemiBold.ttf
        weight: 600
      - asset: fonts/Outfit-Bold.ttf
      - asset: fonts/Outfit-Black.ttf
        weight: 900
      - asset: fonts/Outfit-ExtraBold.ttf
        weight: 800